---
# (C)2016 Brocade Communications Systems, Inc.
# 130 Holger Way, San Jose, CA 95134.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install distro packages
  package:
    name: "{{ tacker_distro_packages }}"
    state: "{{ tacker_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in tacker_developer_constraints %}
      {{ item }}
      {% endfor %}
  when:
    - tacker_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ tacker_requires_pip_packages }}"
    state: "{{ tacker_pip_package_state }}"
    extra_args: >-
      {{ tacker_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Retrieve checksum for venv download
  uri:
    url: "{{ tacker_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: tacker_venv_checksum
  when: tacker_venv_download | bool

- name: Attempt venv download
  get_url:
    url: "{{ tacker_venv_download_url }}"
    dest: "/var/cache/{{ tacker_venv_download_url | basename }}"
    checksum: "sha1:{{ tacker_venv_checksum.content | trim }}"
  register: tacker_get_venv
  when:
    - tacker_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ tacker_bin | dirname }}"
    state: absent
  when:
    - tacker_get_venv | changed

- name: Create tacker venv dir
  file:
    path: "{{ tacker_bin | dirname }}"
    state: directory
  register: tacker_venv_dir
  when:
    - tacker_get_venv | changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ tacker_venv_download_url | basename }}"
    dest: "{{ tacker_bin | dirname }}"
    copy: "no"
  when:
    - tacker_get_venv | changed
  notify:
    - Restart tacker services

- name: Install pip packages
  pip:
    name: "{{ tacker_pip_packages }}"
    state: "{{ tacker_pip_package_state }}"
    virtualenv: "{{ tacker_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ tacker_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when:
    - tacker_get_venv | failed or tacker_get_venv | skipped
  notify:
    - Restart tacker services

- name: Remove python from path first (CentOS, openSUSE)
  file:
    path:  "{{ tacker_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']
    - tacker_get_venv | changed

- name: Update virtualenv path
  shell: |
    find {{ tacker_bin }} -name \*.pyc -delete
    sed -si '1s/^.*python.*$/#!{{ tacker_bin | replace ('/','\/') }}\/python/' {{ tacker_bin }}/*
    virtualenv {{ tacker_bin | dirname }}
  tags:
    - skip_ansible_lint
  when:
    - tacker_get_venv | changed

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: tacker
    option: venv_tag
    value: "{{ tacker_venv_tag }}"
